### ISSUE TITLE
remote cluster如何生成kubeconfig

### ISSUE THREAD

**Issue by jacky68147527** [phosae/x-kubernetes#5]
@phosae 大佬上次支持的apiserver-proxy运行起来了，并且通过生成的Bearer token可以访问remote cluster
现在碰到一个问题，代码里面生成的secureLoopbackClientConfig我转换成kubeconfig后，通过kubectl访问不了集群
有没有办法解决呀，再次寻求您的帮助和指导，感谢~

https rest API调用正常
<img width="914" alt="image" src="https://github.com/phosae/x-kubernetes/assets/6057029/cf52c9d3-7e17-45bd-88ec-a43bd88600a5">

生成kubeconfig，使用kubectl访问异常
kubectl get node --kubeconfig=./proxy.cfg
Unable to connect to the server: x509: certificate signed by unknown authority

kubeconfig内容如下：
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtDZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREF5TVRBd0xnWURWUVFERENkaGNHbHoKWlhKMlpYSXRiRzl2Y0dKaFkyc3RZMnhwWlc1MExXTmhRREUyT1RJd01ERXpORE13SGhjTk1qTXdPREUwTURjeQpNakl5V2hjTk1qUXdPREV6TURjeU1qSXlXakF2TVMwd0t3WURWUVFERENSaGNHbHpaWEoyWlhJdGJHOXZjR0poClkyc3RZMnhwWlc1MFFERTJPVEl3TURFek5ETXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFN0MVk2K2lnWWFXZ0c5Rjd1ckNBeGdTOWQrUkVIYmM5YmFyNFhmNCtjSG1WTFptNUJuYkUwT1BuRwozZGJYaHVMQzBjM21MTU5nYlNURHJjQks3bW92WDhNWDNIcW8yRHhhbFhpTUljeEhWNDYvOG91TkdtaW5CNkF3CmQzRVFDRFE1OHlZM1dpZG9WTmVndkxvcjdGVUl6dXBTc1p3QUtJV0xoZ0JEUUVmZDdDb0tRRFF3cnpUN1MxVnEKYXFkcitpY3RYa3pIN3cyWlBBcE1uTFhsbVpqTjZVclhidHFmRFhxcklCNmtBVzE5bVNWS2lPNld5eG9DVko2eQpTVjN6Y3VvUDR1emc3T1QzcEJwaUZTUWxXQlhFdkRWendOb0Z5dDV6MTVVSVA5UjVteDZFN3ZCWnNQZWxlUE9RCkRwa0tBZ3lTZjNJRDh5Z0o5MWU0d0ltQVplcXRBZ01CQUFHamZEQjZNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVQKQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkpSSApFemxmL1c5YklJUHZ3bzJmMjkzVng5VmVNQ1FHQTFVZEVRUWRNQnVDR1dGd2FYTmxjblpsY2kxc2IyOXdZbUZqCmF5MWpiR2xsYm5Rd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEOG9LbTFQTHlOWHMrekl2TDFNSDA2MGhCSUQKUFVrUVUyK0tLWkcyTDdhaStGS05keXFOVGpqdnpxZFBGeTlrdC81Wk8rTXB4dUNyT0wycmhBT2hBbUJXUjF3QgpENW92STZSaHdqNXlkVFdJNUpjL0lzTCt6ZTg5S2owSEYzbUx0QjltNE1JY1NCSG5Lcm1OMlkwcThjVExYeU94CnJlSjlSM2QyaEQzckZxZVh3bFNLVFRJeHFKVklTN1BjK0FibldRTHBKbnNSVUdwUFJyc1B2Z2U3ZURPUVk0d2sKZ2dkYUd1aGxSRW5La1ZEdElwMGtzSDNKcHJnOXhsS3pjWUpLbU9hTW95YjRKMnFWZm5DeFZGTzdtU1Ztd0s0MApEL29mVmZTQkNZOUcyV1VVYk9iek1CeVRiWDF1MktCU21HeWdYTVpoNUx5eWFrdTBzcGl5TlJJRzkvVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRElUQ0NBZ21nQXdJQkFnSUJBVEFOQmdrcWhraUc5dzBCQVFzRkFEQXlNVEF3TGdZRFZRUUREQ2RoY0dsegpaWEoyWlhJdGJHOXZjR0poWTJzdFkyeHBaVzUwTFdOaFFERTJPVEl3TURFek5ETXdIaGNOTWpNd09ERTBNRGN5Ck1qSXlXaGNOTWpRd09ERXpNRGN5TWpJeVdqQXlNVEF3TGdZRFZRUUREQ2RoY0dselpYSjJaWEl0Ykc5dmNHSmgKWTJzdFkyeHBaVzUwTFdOaFFERTJPVEl3TURFek5ETXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBdwpnZ0VLQW9JQkFRREsvbzViMWJaVUtvUllrMU8wYWN5NmwvbC9lQjRLamRpYnVRQ2V1T1JpRUJxTTBxSHl2Z3ltCi9aYnB3U2JDWlFqbHMvdjFkR3NMUjJ6MVZrMU91cDRjRUVDd3hxWmMxQ1pyc3J1RVQxekNFNm1KM0x2YnQ4NnEKeEErVks4R2RHNkxQOXVJOTUyOFM4dDY2UFFPSEttc3VUekdDcmpBZmNiS3hBOVFLYi84WmV2N1lZeDdESXpoYwpMUE8ycGNaQ3lPM3I0VmVxV2VSUkpzckNKMlRkNmZta2NIcnlEeXZYd2RpTG1Eb1NNWFlIdnZOL0IrYVlUUXYvCmZDbHBpUkNwMjdtVUN0NHBMTmNKcWVSMU1mMmZnNlBzcW1TNkdZRnc3L1lNQXFsSHBodTZNdkMrcFF6M2p3UDUKRG4vSnAyYmhmanJydjF4dmk1ZlpWL3ZiL3Q4MjBrQzNBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQwpwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNVUnhNNVgvMXZXeUNENzhLTm45dmQxY2ZWClhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTQkRKc08zTEpnS1pDV0JMdHFrME9DQzN2ZkN4RW5PN2FuOWIKZU9WWW1rWVBueVYxeVZIMWk0R0N4aGlLOVVGa1VtZXYrdGF0a1RDVkZZTE12QjhXV0NlZFZHM041Vm9KRjh2awpQRXdaUGdjaFZBUHZoak9qN1NSV1BEak96Z1I4Q083SWVKL1YyU0NEbW5QYWd0SERNMUpjdFNiRjc4M2JEOW5uCkpHWSticU42eml2QkFqUElqcXg1ZDlDcmZVbW5SN1ExWEd1blJGNFJGZmFTaTA5VnZkR00yMWxPODFrc2c3dVcKbFBvbEtiT1FrbU40QnEvbGVlMElFN2xZMzdlZUlTLy83ckV5NlRJelJRYm81dGY2OVhMc3hXUFF5R1dVemlqbQovK1IvcjFPdWxhTk9EeGhVYW02a0swRDByYnpiUVVDZk1xYm4xQUlwY3FweUpXdGVFUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    token: 874c3c10-7d30-4b8f-a146-47dc9527d349
```

另外，我如果把kubeconfig的server地址改成实际对外的IP，会报错：
Unable to connect to the server: x509: certificate is valid for 127.0.0.1, not xx.xx.xx.xx
